# Generated by Django 5.2.11 on 2026-03-28 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0092_alter_favoritedocument_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conducteur', models.CharField(db_index=True, max_length=255, verbose_name='Conducteur')),
                ('date_trajet', models.DateField(db_index=True, verbose_name='Date du trajet')),
                ('distance_km', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Distance (km)')),
                ('duree_secondes', models.PositiveIntegerField(default=0, verbose_name='Durée (secondes)')),
                ('gpx_parsed', models.BooleanField(default=False, verbose_name='GPX parsé')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itineraire', to='documents.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Itinéraire',
                'verbose_name_plural': 'Itinéraires',
                'ordering': ['-date_trajet'],
            },
        ),
    ]
